name = "Horse and Tech"
author = "Annika and Jep"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49a59b6742fe54b15d2d2642dc4903eebf7b35c5d8f80ae4d8b653325bccfbd1"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
