name = "Horse and Tech"
author = "Annika and Jep"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a5fc433304646c84b5028b6159333b90fc70d56b164ffba31ad12bf99cc143f"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
