name = "Horse and Tech"
author = "Annika and Jep"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6471921e8d0b0907aa0c7fe9a66c423eaf83dac1c839fba792958f0ab4c67ab4"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
