name = "Horse and Tech"
author = "Annika and Jep"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24204c313f2ecc3252333e92a6deed779e3dbdf20f896f17196326295196e96f"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
